### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by josh146** [XanaduAI/strawberryfields#2]
It would be nice to specify 'sampling' as well as the number of shots to sample - if this is specified, the simulation should then sample the results of the measurement operators.

The fastest way to do this is to 'cheat' and simply run the circuit once *without* the measurement operators (as these reset the modes to the vacuum state), and then sample the Fock state probabilities/quadrature probabilities of the qumodes that are to be measured.

This feature should also ideally be supported in Blackbird in a way that doesn't require the user to modify the engine queue to remove existing measurement gates. Perhaps as a keyword argument when running the engine?

`eng.run(n_subsystems=3, backend=b, sampling=50)`

In this case, the frontend would:
1. 'hide' the measurement operators from the queue, but remember the qumodes to be measured
2. extract the required probability distribution and sample respective qumodes 50 times
3. return the **list** of sampled values to the user, perhaps using the attribute `reg.val` (or defining `reg.sample`?)

**Comment by ziofil** [comment]
What if one wanted to perturb the initial state before the transformation?

**Comment by josh146** [comment]
Hi @ziofil, can you clarify what you mean/what operation you would like?

**Comment by ziofil** [comment]
Yeah sorry, I was very unclear. I seem to understand that the sampling you are proposing could work because you can turn the output into a probability distribution to sample from. What I was considering is that this would not work if one wanted to sample a few _initial_ states, apply a transformation (say, a channel) and then use the final results.
I would love this feature, to run a few optimizations with different initial conditions in parallel.

**Comment by co9olguy** [comment]
A particular restricted solution for this is implemented in #100.
