### ISSUE TITLE
Adding Parity as an Observable

### ISSUE THREAD

**Issue by Lucaman99** [XanaduAI/strawberryfields#386]
(In reference to this Issue raised over in the Pennylane repository: https://github.com/XanaduAI/pennylane/issues/193)

As @artix41 said in his issue, it might be interesting to try to incorporate a parity observable, 
defined as (-1)^N, into Strawberry Fields, so that it can eventually be incorporated into Pennylane.

I'd love to try to tackle this issue, where would be the best place to start / where in the codebase should a feature like this be added? @josh146

**Comment by Lucaman99** [comment]
I don't think it would be too difficult to take the pre-existing implementation of the number operator in the SF code and calculate (-1)^N by expanding (-1)^x in a power series, with some finite truncation.

**Comment by josh146** [comment]
Hi @Lucaman99! 

> I'd love to try to tackle this issue, where would be the best place to start / where in the codebase should a feature like this be added?

The best place would probably be the `backend/states.py` file; this contains all the methods for manipulating and post-processing state vectors that are returned from the Strawberry Fields backends. 

Something to keep in note is that there are separate state objects, one for the Fock backends, and one for the Gaussian backends! This is because the two states differ in their representation; a Fock-basis density matrix, and a Gaussian distribution respectively.

> so that it can eventually be incorporated into Pennylane.

In addition, if you want to contribute to PennyLane, let me know I can direct you to some 'good first issues' in the PennyLane repository 🙂

**Comment by Lucaman99** [comment]
@josh146 Thanks for your comment, this was super helpful. I just created a method called `parity_expectation` in `backend/state.py` file, inside the `BaseFockState` class. I also created a basic test case. 

I'm going to create a "Work in Progress" pull request, so you can take a look and make sure I'm not making any big mistakes. 😄 

Also, the method I implemented unfortunately only supports pure states right now (I'm not totally sure how to go about implementing this function in the code for mixed states, do you have any suggestions?)

> let me know I can direct you to some 'good first issues' in the PennyLane repositor

That would be great, thanks so much! I'd love to try to tackle a few more issues!

**Comment by thisac** [comment]
Hi @Lucaman99. Thank you very much for contributing to Strawberry Fields. We'll have a closer look at the PR and get back to you with any feedback we might have. :slightly_smiling_face:
