### ISSUE TITLE
qchem.read_gamess read w with scale factor

### ISSUE THREAD

**Issue by GongSiqiu** [XanaduAI/strawberryfields#699]
### Before posting a feature request

- [X] I have searched exisisting GitHub issues to make sure the feature request does not already exist.

### Feature details

Now the function the w read by qchem.read_gamess are not multiplied by the SCLFAC.  Without it, the frequencies will bias a lot from experiments. So is it possible to add this feature that get w and times them with SCLFAC

### How important would you say this feature is?

1: Not important. Would be nice to have.

**Comment by thisac** [comment]
Hi @GongSiqiu, and thanks for opening up this feature request. Could you clarify the feature that you would like added; adding some more detail to this request?

**Comment by soranjh** [comment]
Hi @GongSiqiu. Could you please confirm that by SCLFAC, you mean the empirical [scaling factors](https://cccbdb.nist.gov/vibnotes.asp) that are used to correct vibrational frequencies obtained from computational methods to better match experimental data? 

If it is the case, such corrections are better to be done on the user side, instead of having hard-coded scaling factors in SF. We can help you with that if you please provide us with the code and the data you are using. I also recommend opening a topic for this in our discussion [forum](https://discuss.pennylane.ai/top/all) if you need help with correcting the frequencies.

Please feel free to let us know if you have any questions.

**Comment by GongSiqiu** [comment]
Yes, I do mean that. I just do it like this:
`ri, m, wi, Li=qchem.read_gamess('CH2O2_GS.out')`
`rf, m, wf, Lf=qchem.read_gamess('CH2O2_ES.out')`
`wi=wi*0.964`
`wf=wf*0.964`

Because GAMESS always prints results without scaling, I don't known whether it will affect normal modes.

**Comment by GongSiqiu** [comment]
I write GAMESS input file with command ` $FORCE METHOD=ANALYTIC  SCLFAC = 0.97 $END` but it worth noting that

>The output always prints unscaled frequencies, so this value is used only during the thermochemical analysis. 

So I think read_gamess should scale frequencies with the SCLFAC

**Comment by soranjh** [comment]
Thanks @GongSiqiu for the suggestion, we are looking into this.

**Comment by thisac** [comment]
Added in #704 and part of latest release (v0.23.0). @GongSiqiu
